= Papstehrenwort: task commitment system for our hackerspace

This project is currently being rewritten and not yet in a usable state.

== Idea
* Members of the space can commit themselves to a task that needs to be done regularly
* They get notified (via email) everytime when the task is to do
* After doing the task they enter that information into the system

== Spec

=== Basic Architecture

* There is a list of tasks created by entitled users / admins. Each task consists of
** Title
** Description
** Frequency
** Time that a task is overdue after
* Each user may commit themselves to zero or more tasks
** Multiple users per task are also possible.
* Every time a task is to do the user gets notified via email .
* After they have done the task they can confirm that fact.
* When the task is overdue another notification will be sent. If the task hasn't been done after it is "double overdue" the user will be disassigned.

=== Frequencies

A frequency specifies how often a task must be done. We need a representation that is powerful and means something to users. Therefore we propose a solution based on the human calendar. Valid values would be for example:

* Every two weeks
* Each month
* Every two days
* Every two months

Depending on the frequency the overdue time also must vary. It is to be proposed wether the overdue time must be entered manually or gets calculated automatically.

We propose that a crond's approach should be used since cron offers relatively powerful and generic means of denoting frequencies. For parsing and representation of cron requencies http://hackage.haskell.org/package/cron[cron] could be used.

=== Ideas

* GPG- or Client Certificate-Auth
* Public shaming feature

== Implementation

=== Web framework

http://hackage.haskell.org/package/servant-blaze[servant-blaze]

=== Storage

* sqlite (postgres(t)?)

== TODO

* Less frontend dependencies
** no npm and bower
** CoffeeScript can be removed?

== Built by these people

@Profpatsch
@sternenseemann